### ISSUE TITLE
Improve debugger tab management

### ISSUE THREAD

**Issue by thrashdin** [neil-lindquist/SLIMA#14]
There are two things you might want to look into.

1) For some reason if debugger opens, it always opens near the repl tab, and if I move it's tab somewhere else and press smth like `step-into call` a new debugger tab opens. Near the repl.

2) There's no option to look into variables -- such as class instances and vectors, to see what's inside. In Emacs you can do that by pressing them.

I'm trying to help by finding this stuff)

**Comment by neil-lindquist** [comment]
The debugger tab currently doesn't have good support for being anywhere except the REPL's pane (specifically that pane that was created for the REPL), so spawning new debuggers there is currently the best option.  This mainly comes from the API used for some of the tab management.  If I can figure out an API that doesn't depend so much on panes, then remembering the pane for debuggers shouldn't be too hard to implement.


For the second part, that's what #2 is about (and related to #7).  I'm expecting that to take some effort and I'm hoping to deal with #8 first instead of implementing more UI with a library that I'm hoping to replace.  I'm hoping to tackle this in May or June.

**Comment by markboston34** [comment]
i'd be willing to help out

**Comment by neil-lindquist** [comment]
The second part of this issue was taken care of in the latest release.
The first part requires finding an API in Atom for either getting the pane that a tab (I think the Atom term here is view) belongs to, or for destroying a tab (view) without knowing the pane it's in.  I'm not sure if there are either of them, but I haven't spent much time looking.  There might be another spot that the REPL pane gets used that might need to be replaced as well, but I'm not sure off hand.
Once the code is no longer dependent on everything being in the REPL pane, the actual request to do-what-i-mean with tabs *shouldn't* be too hard.

As a side note, I'm updating the title of the issue to more accurately label what's left in the issue

**Comment by neil-lindquist** [comment]
Julia's Juno IDE seems to have figured this out. It might be worth poking around in its internals for ideas on tab management.

https://github.com/JunoLab/atom-julia-client

**Comment by neil-lindquist** [comment]
I've reworked things to avoid needed a fixed pane for tab management by looking up the current pane when it's needed (which is how Juno works around the issue).  I've gotten the tab spawning in what seems like an intuitive system:
* The frame info tab always spawns in the same pane as the associated debugger
* The inspector and any top level debugger uses Atom's default placement, which I think works out as
  * In the current pane the first time it's opened (so almost certainly the REPL pane)
  * In the same tab as before for subsequent opens, unless panes have rearranged
* Any debuggers that are not top level appear in the same pane as the next debugger up the stack

Let me know if any of these seem like they're not actually intuitive or convenient. Or feel free to [try the current master branch](https://github.com/neil-lindquist/SLIMA/wiki/Using-Development-Versions-of-SLIMA).
