### ISSUE TITLE
y-or-n-p function doesn't work

### ISSUE THREAD

**Issue by uUJsd7PX** [neil-lindquist/SLIMA#21]
Function (y-or-n-p "y/n: "))) crashes when entering y or n with "unmatched close parenthesis" error. Works correctly with other input (asks again). Also writing activates autocomplete, which it shouldn't.

**Comment by uUJsd7PX** [comment]
Also I'm not sure if added " (y or n)" is required, since I'd like to have my own text to be shown, like [y/n] for example.

**Comment by neil-lindquist** [comment]
I actually find it really interesting that it sometimes will take values from the end of the command, since commands are evaluated via a function call (swank:eval-for-emacs IIRC), and instead of using the standard input.  I don't know if there's a way to implement it how you're expecting, but it should probably be at least be made consistant.

For autocomplete, it seems like it might be useful for some types of user input where an S-expression is expected (like `read`).  And there's no way to differentiate between different types of reads, since SLIMA just gets a message that text is expected from the user input stream.  So, I'm not sure if disabling it is ideal (or how to even do that).

The " (y or n)" is added by your lisp implementation, so there's nothing I can do on that front.

**Comment by neil-lindquist** [comment]
I had a chance to look at this, and it's behaving the way I'd expect it.  When `(y-or-n-p "test")))` is evaluated, it reads the first form , evaluates it, then starts reading again (at least on SBCL).  Since the expression being evaluated doesn't go through standard input, y-or-n-p won't ever see it.  So, the function gets resolved normally, then goes to read any other forms and gets `))` which is an unmatched closed parenthesis.
