### ISSUE TITLE
Real Time Inspections?

### ISSUE THREAD

**Issue by itmuckel** [neil-lindquist/SLIMA#31]
Is it possible to get real time code analysis?

The simplest thing that really would boost my productivity, would be, if undefined functions or variables would get underlined.

When compiling a system you get warnings etc. from SBCL. It would be nice if these errors/warnings could be extracted, so Atom could mark the critical spots. Unfortunately it doesn't show line numbers/position of the errors.

Any ideas?

**Comment by thrashdin** [comment]
It's a feature called flycheck 
Even Emacs doesn't have it atm

In discord we discussed it with several ppl. 
Ideas were about running a parallel sbcl process.

It's umm, kinda hard to implement, since there's no such functionality anywhere.

**Comment by itmuckel** [comment]
Hmmm, I also found [this article](https://www.snellman.net/blog/archive/2007-12-19-pretty-sbcl-backtraces.html), but I have no idea how stable that code is. 🤔 Looks doable to me to run a process like this, outputting errors with positions. Slima could then grab that information and highlight the problematic lines.

**Comment by neil-lindquist** [comment]
I looked a little at this, and while continuously linting the code is difficult, it shouldn't be hard to mark issues with code that gets compiled.  Specifically, swank provides the compiler notes when things are compiled with ctrl+c and ctrl+k, which include source location.  Plus, since it's implemented in swank it should be portable across lisps.
Unfortunately, code evaled in the REPL, code that's compiled directly by things like `(load "file.lisp")` or `(compile "file.lisp")` and load time warnings (such as redefinition warnings) don't have warnings collected.

[2.3.1](https://github.com/neil-lindquist/SLIMA/issues/30) needs to be tested and published before I start on this though.

There is also https://atom.io/packages/linter-slime-lint, but I have no clue on the quality of it.

**Comment by mmontone** [comment]
There's slime-load-system in SLIME, that loads an ASDF system and opens a buffer with the found warnings, pointing to where the warning occurred. That may be worth a look.

**Comment by neil-lindquist** [comment]
The big issue for this is converting Swank's source location objects to a form that I can pass to Atom's linter package.  I've spent some time on this, but it's not straightforward for all of the cases.

**Comment by neil-lindquist** [comment]
I've gotten support implemented for highlighting the compilation notes in the release candidate I've just finished.

Because of the dynamic and image-based nature of Common Lisp, I don't think there is an accurate way to statically analyze the code for real time reporting.  So, I'm going to close this issue, unless someone has an idea on how to do this accurately.
