### ISSUE TITLE
Compile with dependencies

### ISSUE THREAD

**Issue by justjoheinz** [neil-lindquist/SLIMA#48]
```list
(require :cells)
(use-package :cells)

(defmodel person ()
  (
   (lastn :accessor lastn :initarg :lastn
              :initform (c-in 0))
   (firstn :accessor firstn :initarg :firstn
               :initform (c-in 0))
   (fulln :accessor fulln
              :initform (c? (list (lastn self) ", " (firstn self))))
   ))

(defun testme ()
   (let ((p (make-instance 'person)))
     (setf (lastn p) 'K)
     (setf (firstn p) 'M)
     (format t "last-name is ~a~%" (lastn p))
     (format t "first-name is ~a~%" (firstn p))
     (format t "full-name is ~a~%" (fulln p))
     )
   )
```

I can't get this to work with Atom Slima at all. Slima refuses to resolve the definition of defmodel. The code works fine if I use sbcl directly but not from within Atom. It does not matter whether I try to compile functions or the whole buffer. There seem to be some unrelated (?) problems as well, which I am getting with simpler projects to. e.g. warnings like "Cannot use index position if editor is not present" and in the console "Unknown key in compilation note: ":references" raised by the swank client. Can you advise what I might be doing wrong, or what kind of information might be useful to provide?

**Comment by neil-lindquist** [comment]
It works for me when using "compile function" on each toplevel form, so I'm not sure where the error is there.

Compiling the whole buffer requires a few tweaks.
First, the `require` and `use-package` forms need to be wrapped in `(eval-when (:compile-toplevel :load-toplevel)`.  Otherwise, it reads the other forms before `cl-user`  knows to use symbols from `cells`.
Second, utils-kt (a dependency of cells) causes some asdf warnings, which cause swank to label the compilation a failure.  So, that system (or cells) needs to be loaded either directly in the repl (or using `ql:quickload` to take care of the warnings).

The warnings you listed shouldn't be affecting your compilation.

**Comment by justjoheinz** [comment]
Thank you very much for your explanation! I got it to work.

**Comment by neil-lindquist** [comment]
I'm glad to hear it.
